### ISSUE TITLE
Outy break SSR : window is not defined

### ISSUE THREAD

**Issue by ylacaute** [souporserious/outy#2]
I created an issue on mdbreact (https://github.com/mdbootstrap/bootstrap-material-design/issues/196) but I think the problem come from Outy.

What do you think ?

**Comment by souporserious** [comment]
Ah yes, there should be checks to make sure `document` and `window` are defined. Please feel free to start a PR if you have a solution and I can merge it and cut a new release.

**Comment by ylacaute** [comment]
I have made some tests, Outy works with SSR. I am able to use it alone and when I extract Outy from mdbreact I still have the problem.

The problem seems to come from another library used by mdbreact...
